version: "3.8"
services:
  nginx:
    image: nginx:latest
    networks:
      - "games-net"
    ports:
      - target: 80
        published: 80
        protocol: tcp
    volumes:
      - type: bind
        source: ./nginx.conf
        target: /etc/nginx/nginx.conf
    depends_on:
      - "front-end"
  front-end:
    image: numphries/front-end:latest
    build: ./front-end
    networks: 
      - "games-net"
    depends_on:
      - "mysql"
    environment: 
        MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  away-team-generator:
    image: numphries/away-team-generator:latest
    build: ./away-team-generator
    networks:
      - "games-net"
  home-team-generator:
    image: numphries/home-team-generator:latest
    build: ./home-team-generator
    networks:
      - "games-net"
  score-generator:
    image: numphries/score-generator:latest
    build: ./score-generator
    networks:
      - "games-net"
    depends_on:
      - "home-team-generator"
      - "away-team-generator"
  mysql:
    image: numphries/games-db:latest
    build: ./db
    volumes:
      - type: volume
        source: games-vol
        target: /var/lib/mysql
    networks:
      - "games-net"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: games_db
volumes:
  games-vol:
networks:
  games-net:
    #driver: overlay